###
POST http://localhost:3400/api/v1/workers/new-worker  HTTP/1.1
Content-Type: application/json

{
    "first_name": "JULIO ",
    "last_name": "CANON",
    "work" : [{
        "id_work" : "1",
        "name_work" : "PILOTO"
    }],
    "type_document" : "cedula",
    "document_number" : "1054521362"    
}

###
GET http://localhost:3400/api/v1/workers/  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3400/api/v1/workers/651b23796f6179d61af3a424  HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3400/api/v1/workers/651b23796f6179d61af3a424  HTTP/1.1
Content-Type: application/json

{
    "first_name": "LUIS ",
    "last_name": "CANON",
    "work" : [{
        "id_work" : "1",
        "name_work" : "PANADERO"
    }],
    "type_document" : "cedula",
    "document_number" : "1056121362"    
}


###
DELETE http://localhost:3400/api/v1/workers/651b224a6f6179d61af3a411  HTTP/1.1
Content-Type: application/json




